apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-read-only
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-read-only-binding
subjects:
  - kind: User
    name: <YOUR_USERNAME>  # Replace with your K8s username
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: nginx-read-only
  apiGroup: rbac.authorization.k8s.io


